### Obtain

In [1040]:
import polars as pl
from datetime import date, time

In [1041]:
df2_prim = pl.read_excel('datasets/02_ROTURAS_RED_PRIMARIA_SECUNDARIA_PIURA.xlsx', sheet_name='ROTURAS_RED_PRIMARIA')
df2_sec = pl.read_excel('datasets/02_ROTURAS_RED_PRIMARIA_SECUNDARIA_PIURA.xlsx', sheet_name='FUGAS_RED_SECUNDARIA')

df2_prim.head()

shape: (5, 12)
┌──────────┬────────┬──────────────┬─────┬───┬────────────┬──────────────┬────────────┬────────────┐
│ CONEXION ┆ SECTOR ┆ CDESTIPSER   ┆ MES ┆ … ┆ fecha_fin  ┆ hora_fin     ┆ latitud    ┆ longitud   │
│ ---      ┆ ---    ┆ ---          ┆ --- ┆   ┆ ---        ┆ ---          ┆ ---        ┆ ---        │
│ i64      ┆ str    ┆ str          ┆ i64 ┆   ┆ date       ┆ datetime[ms] ┆ f64        ┆ f64        │
╞══════════╪════════╪══════════════╪═════╪═══╪════════════╪══════════════╪════════════╪════════════╡
│ 15       ┆ S74    ┆ AG:          ┆ 7   ┆ … ┆ 2025-07-14 ┆ 1899-12-31   ┆ -5.222965  ┆ -80.627582 │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 09:59:24.144 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
│ 17       ┆ S74    ┆ AG:          ┆ 6   ┆ … ┆ 2025-06-04 ┆ 1899-12-31   ┆ -5.16027   ┆ -80.631254 │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 05:13:25.844 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
│ 18       ┆ S74    ┆ AG:          ┆ 10  ┆ … ┆ 2025-10-15 ┆ 1899-12-31   ┆ -5.188223  ┆ -80.622336 │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 11:58:01.844 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
│ 23       ┆ S74    ┆ AG:          ┆ 1   ┆ … ┆ 2025-01-15 ┆ 1899-12-31   ┆ -5.197104  ┆ -80.587974 │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 16:03:23.544 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
│ 32       ┆ S74    ┆ AG:          ┆ 12  ┆ … ┆ 2025-12-24 ┆ 1899-12-31   ┆ -80.619972 ┆ -5.224533  │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 00:48:45.822 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
└──────────┴────────┴──────────────┴─────┴───┴────────────┴──────────────┴────────────┴────────────┘

In [1042]:
df2_sec.head()

shape: (5, 12)
┌──────────┬────────┬──────────────┬─────┬───┬────────────┬──────────────┬────────────┬────────────┐
│ CONEXION ┆ SECTOR ┆ CDESTIPSER   ┆ MES ┆ … ┆ fecha_fin  ┆ hora_fin     ┆ latitud    ┆ longitud   │
│ ---      ┆ ---    ┆ ---          ┆ --- ┆   ┆ ---        ┆ ---          ┆ ---        ┆ ---        │
│ i64      ┆ str    ┆ str          ┆ i64 ┆   ┆ date       ┆ datetime[ms] ┆ f64        ┆ f64        │
╞══════════╪════════╪══════════════╪═════╪═══╪════════════╪══════════════╪════════════╪════════════╡
│ 1        ┆ S74    ┆ AG:          ┆ 6   ┆ … ┆ 2025-06-13 ┆ 1899-12-31   ┆ -5.193186  ┆ -80.635189 │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 00:50:45.900 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
│ 2        ┆ S74    ┆ AG:          ┆ 1   ┆ … ┆ 2025-01-29 ┆ 1899-12-31   ┆ -5.176467  ┆ -80.646468 │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 01:17:34.900 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
│ 3        ┆ S74    ┆ AG:          ┆ 10  ┆ … ┆ 2025-10-17 ┆ 1899-12-31   ┆ -5.20468   ┆ -80.617352 │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 14:15:22.084 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
│ 4        ┆ S74    ┆ AG:          ┆ 4   ┆ … ┆ 2025-04-13 ┆ 1899-12-31   ┆ -5.160009  ┆ -80.619713 │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 23:27:13.856 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
│ 4        ┆ S74    ┆ AG:          ┆ 4   ┆ … ┆ 2025-04-17 ┆ 1899-12-31   ┆ -80.619713 ┆ -5.160009  │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 20:50:24.560 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
└──────────┴────────┴──────────────┴─────┴───┴────────────┴──────────────┴────────────┴────────────┘

In [1043]:
df2_prim.describe()

shape: (9, 13)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ CONEXION   ┆ SECTOR ┆ CDESTIPSE ┆ … ┆ fecha_fin ┆ hora_fin  ┆ latitud   ┆ longitud  │
│ ---        ┆ ---        ┆ ---    ┆ R         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ f64        ┆ str    ┆ ---       ┆   ┆ str       ┆ str       ┆ f64       ┆ f64       │
│            ┆            ┆        ┆ str       ┆   ┆           ┆           ┆           ┆           │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 726.0      ┆ 726    ┆ 726       ┆ … ┆ 726       ┆ 726       ┆ 726.0     ┆ 726.0     │
│ null_count ┆ 0.0        ┆ 0      ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 5183.84022 ┆ null   ┆ null      ┆ … ┆ 2025-06-2 ┆ 1899-12-3 ┆ -12.77289 ┆ -73.04698 │
│            ┆            ┆        ┆           ┆   ┆ 6 02:54:3 ┆ 1 12:24:4 ┆ 1         ┆ 1         │
│            ┆            ┆        ┆           ┆   ┆ 2.727272  ┆ 7.341000  ┆           ┆           │
│ std        ┆ 3008.16745 ┆ null   ┆ null      ┆ … ┆ null      ┆ null      ┆ 22.705702 ┆ 22.70561  │
│            ┆ 3          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ min        ┆ 15.0       ┆ S10    ┆ AG: Conex ┆ … ┆ 2025-01-0 ┆ 1899-12-3 ┆ -80.68765 ┆ -80.69132 │
│            ┆            ┆        ┆ iones Dom ┆   ┆ 3         ┆ 1 00:01:5 ┆ 3         ┆ 2         │
│            ┆            ┆        ┆ iciliaria ┆   ┆           ┆ 8.439000  ┆           ┆           │
│            ┆            ┆        ┆ s  …      ┆   ┆           ┆           ┆           ┆           │
│ 25%        ┆ 2562.0     ┆ null   ┆ null      ┆ … ┆ 2025-03-2 ┆ 1899-12-3 ┆ -5.199978 ┆ -80.65302 │
│            ┆            ┆        ┆           ┆   ┆ 0         ┆ 1 06:18:3 ┆           ┆ 6         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 3.302000  ┆           ┆           │
│ 50%        ┆ 5155.0     ┆ null   ┆ null      ┆ … ┆ 2025-06-1 ┆ 1899-12-3 ┆ -5.188223 ┆ -80.62968 │
│            ┆            ┆        ┆           ┆   ┆ 9         ┆ 1 12:52:5 ┆           ┆           │
│            ┆            ┆        ┆           ┆   ┆           ┆ 0.080000  ┆           ┆           │
│ 75%        ┆ 8107.0     ┆ null   ┆ null      ┆ … ┆ 2025-09-2 ┆ 1899-12-3 ┆ -5.177773 ┆ -80.59925 │
│            ┆            ┆        ┆           ┆   ┆ 5         ┆ 1 18:24:1 ┆           ┆ 3         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 6.688000  ┆           ┆           │
│ max        ┆ 10318.0    ┆ S84    ┆ AG: Conex ┆ … ┆ 2026-01-0 ┆ 1899-12-3 ┆ -5.139109 ┆ -5.143028 │
│            ┆            ┆        ┆ iones Dom ┆   ┆ 4         ┆ 1 23:58:4 ┆           ┆           │
│            ┆            ┆        ┆ iciliaria ┆   ┆           ┆ 5.800000  ┆           ┆           │
│            ┆            ┆        ┆ s  …      ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [1044]:
df2_sec.describe()

shape: (9, 13)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ CONEXION   ┆ SECTOR ┆ CDESTIPSE ┆ … ┆ fecha_fin ┆ hora_fin  ┆ latitud   ┆ longitud  │
│ ---        ┆ ---        ┆ ---    ┆ R         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ f64        ┆ str    ┆ ---       ┆   ┆ str       ┆ str       ┆ f64       ┆ f64       │
│            ┆            ┆        ┆ str       ┆   ┆           ┆           ┆           ┆           │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 11159.0    ┆ 11159  ┆ 11159     ┆ … ┆ 11159     ┆ 11159     ┆ 11159.0   ┆ 11159.0   │
│ null_count ┆ 0.0        ┆ 0      ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 5130.13594 ┆ null   ┆ null      ┆ … ┆ 2025-06-2 ┆ 1899-12-3 ┆ -12.40051 ┆ -73.42002 │
│            ┆ 4          ┆        ┆           ┆   ┆ 6 14:05:2 ┆ 1 12:03:5 ┆ 6         ┆ 8         │
│            ┆            ┆        ┆           ┆   ┆ 9.706963  ┆ 8.652000  ┆           ┆           │
│ std        ┆ 2989.46028 ┆ null   ┆ null      ┆ … ┆ null      ┆ null      ┆ 22.187622 ┆ 22.187788 │
│            ┆ 3          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ min        ┆ 1.0        ┆ S1     ┆ AG: Conex ┆ … ┆ 2025-01-0 ┆ 1899-12-3 ┆ -80.69158 ┆ -80.69289 │
│            ┆            ┆        ┆ iones Dom ┆   ┆ 1         ┆ 1 00:00:0 ┆ 2         ┆ 6         │
│            ┆            ┆        ┆ iciliaria ┆   ┆           ┆ 5.298000  ┆           ┆           │
│            ┆            ┆        ┆ s  …      ┆   ┆           ┆           ┆           ┆           │
│ 25%        ┆ 2526.0     ┆ null   ┆ null      ┆ … ┆ 2025-03-2 ┆ 1899-12-3 ┆ -5.201284 ┆ -80.65276 │
│            ┆            ┆        ┆           ┆   ┆ 1         ┆ 1 06:04:2 ┆           ┆ 3         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 2.510000  ┆           ┆           │
│ 50%        ┆ 5139.0     ┆ null   ┆ null      ┆ … ┆ 2025-06-2 ┆ 1899-12-3 ┆ -5.188223 ┆ -80.63072 │
│            ┆            ┆        ┆           ┆   ┆ 1         ┆ 1 12:03:3 ┆           ┆ 9         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 7.028000  ┆           ┆           │
│ 75%        ┆ 7710.0     ┆ null   ┆ null      ┆ … ┆ 2025-09-2 ┆ 1899-12-3 ┆ -5.177251 ┆ -80.60581 │
│            ┆            ┆        ┆           ┆   ┆ 8         ┆ 1 18:06:0 ┆           ┆           │
│            ┆            ┆        ┆           ┆   ┆           ┆ 2.352000  ┆           ┆           │
│ max        ┆ 10340.0    ┆ S9     ┆ AG: Conex ┆ … ┆ 2026-01-0 ┆ 1899-12-3 ┆ -5.13937  ┆ -5.139109 │
│            ┆            ┆        ┆ iones Dom ┆   ┆ 2         ┆ 1 23:59:5 ┆           ┆           │
│            ┆            ┆        ┆ iciliaria ┆   ┆           ┆ 2.912000  ┆           ┆           │
│            ┆            ┆        ┆ s  …      ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### Reto 1

In [1045]:
# 1. Remover duplicados

df2_prim = df2_prim.unique(subset=['CONEXION', 'CATEGORIA', 'fecha_inicio'], keep='first')
df2_sec = df2_sec.unique(subset=['CONEXION', 'CATEGORIA', 'fecha_inicio'], keep='first')

In [1046]:
df2_prim.describe()

shape: (9, 13)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ CONEXION   ┆ SECTOR ┆ CDESTIPSE ┆ … ┆ fecha_fin ┆ hora_fin  ┆ latitud   ┆ longitud  │
│ ---        ┆ ---        ┆ ---    ┆ R         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ f64        ┆ str    ┆ ---       ┆   ┆ str       ┆ str       ┆ f64       ┆ f64       │
│            ┆            ┆        ┆ str       ┆   ┆           ┆           ┆           ┆           │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 722.0      ┆ 722    ┆ 722       ┆ … ┆ 722       ┆ 722       ┆ 722.0     ┆ 722.0     │
│ null_count ┆ 0.0        ┆ 0      ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 5179.53601 ┆ null   ┆ null      ┆ … ┆ 2025-06-2 ┆ 1899-12-3 ┆ -12.71039 ┆ -73.10947 │
│            ┆ 1          ┆        ┆           ┆   ┆ 6 09:16:2 ┆ 1 12:25:1 ┆ 2         ┆ 6         │
│            ┆            ┆        ┆           ┆   ┆ 7.257617  ┆ 5.874000  ┆           ┆           │
│ std        ┆ 3011.43187 ┆ null   ┆ null      ┆ … ┆ null      ┆ null      ┆ 22.62264  ┆ 22.622416 │
│            ┆ 2          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ min        ┆ 15.0       ┆ S10    ┆ AG: Conex ┆ … ┆ 2025-01-0 ┆ 1899-12-3 ┆ -80.68765 ┆ -80.69132 │
│            ┆            ┆        ┆ iones Dom ┆   ┆ 3         ┆ 1 00:01:5 ┆ 3         ┆ 2         │
│            ┆            ┆        ┆ iciliaria ┆   ┆           ┆ 8.439000  ┆           ┆           │
│            ┆            ┆        ┆ s  …      ┆   ┆           ┆           ┆           ┆           │
│ 25%        ┆ 2557.0     ┆ null   ┆ null      ┆ … ┆ 2025-03-2 ┆ 1899-12-3 ┆ -5.199978 ┆ -80.65328 │
│            ┆            ┆        ┆           ┆   ┆ 0         ┆ 1 06:18:3 ┆           ┆ 8         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 3.302000  ┆           ┆           │
│ 50%        ┆ 5151.0     ┆ null   ┆ null      ┆ … ┆ 2025-06-1 ┆ 1899-12-3 ┆ -5.188223 ┆ -80.62968 │
│            ┆            ┆        ┆           ┆   ┆ 9         ┆ 1 12:52:5 ┆           ┆           │
│            ┆            ┆        ┆           ┆   ┆           ┆ 0.080000  ┆           ┆           │
│ 75%        ┆ 8107.0     ┆ null   ┆ null      ┆ … ┆ 2025-09-2 ┆ 1899-12-3 ┆ -5.177773 ┆ -80.59925 │
│            ┆            ┆        ┆           ┆   ┆ 5         ┆ 1 18:24:5 ┆           ┆ 3         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 4.476000  ┆           ┆           │
│ max        ┆ 10318.0    ┆ S84    ┆ AG: Conex ┆ … ┆ 2026-01-0 ┆ 1899-12-3 ┆ -5.139109 ┆ -5.143028 │
│            ┆            ┆        ┆ iones Dom ┆   ┆ 4         ┆ 1 23:58:4 ┆           ┆           │
│            ┆            ┆        ┆ iciliaria ┆   ┆           ┆ 5.800000  ┆           ┆           │
│            ┆            ┆        ┆ s  …      ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [1047]:
df2_sec.describe()

shape: (9, 13)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ CONEXION   ┆ SECTOR ┆ CDESTIPSE ┆ … ┆ fecha_fin ┆ hora_fin  ┆ latitud   ┆ longitud  │
│ ---        ┆ ---        ┆ ---    ┆ R         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ f64        ┆ str    ┆ ---       ┆   ┆ str       ┆ str       ┆ f64       ┆ f64       │
│            ┆            ┆        ┆ str       ┆   ┆           ┆           ┆           ┆           │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 10860.0    ┆ 10860  ┆ 10860     ┆ … ┆ 10860     ┆ 10860     ┆ 10860.0   ┆ 10860.0   │
│ null_count ┆ 0.0        ┆ 0      ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 5134.38849 ┆ null   ┆ null      ┆ … ┆ 2025-06-2 ┆ 1899-12-3 ┆ -12.44625 ┆ -73.37427 │
│            ┆            ┆        ┆           ┆   ┆ 7 05:49:0 ┆ 1 12:04:1 ┆ 7         ┆ 6         │
│            ┆            ┆        ┆           ┆   ┆ 7.624309  ┆ 1.149000  ┆           ┆           │
│ std        ┆ 2991.15198 ┆ null   ┆ null      ┆ … ┆ null      ┆ null      ┆ 22.250462 ┆ 22.250635 │
│            ┆ 8          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ min        ┆ 1.0        ┆ S1     ┆ AG: Conex ┆ … ┆ 2025-01-0 ┆ 1899-12-3 ┆ -80.69158 ┆ -80.69289 │
│            ┆            ┆        ┆ iones Dom ┆   ┆ 1         ┆ 1 00:00:0 ┆ 2         ┆ 6         │
│            ┆            ┆        ┆ iciliaria ┆   ┆           ┆ 5.298000  ┆           ┆           │
│            ┆            ┆        ┆ s  …      ┆   ┆           ┆           ┆           ┆           │
│ 25%        ┆ 2532.0     ┆ null   ┆ null      ┆ … ┆ 2025-03-2 ┆ 1899-12-3 ┆ -5.201284 ┆ -80.65276 │
│            ┆            ┆        ┆           ┆   ┆ 2         ┆ 1 06:04:2 ┆           ┆ 3         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 0.278000  ┆           ┆           │
│ 50%        ┆ 5139.0     ┆ null   ┆ null      ┆ … ┆ 2025-06-2 ┆ 1899-12-3 ┆ -5.188223 ┆ -80.63072 │
│            ┆            ┆        ┆           ┆   ┆ 2         ┆ 1 12:03:3 ┆           ┆ 9         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 7.028000  ┆           ┆           │
│ 75%        ┆ 7717.0     ┆ null   ┆ null      ┆ … ┆ 2025-09-2 ┆ 1899-12-3 ┆ -5.176989 ┆ -80.60554 │
│            ┆            ┆        ┆           ┆   ┆ 9         ┆ 1 18:05:5 ┆           ┆ 8         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 0.972000  ┆           ┆           │
│ max        ┆ 10340.0    ┆ S9     ┆ AG: Conex ┆ … ┆ 2026-01-0 ┆ 1899-12-3 ┆ -5.13937  ┆ -5.139109 │
│            ┆            ┆        ┆ iones Dom ┆   ┆ 2         ┆ 1 23:59:5 ┆           ┆           │
│            ┆            ┆        ┆ iciliaria ┆   ┆           ┆ 2.912000  ┆           ┆           │
│            ┆            ┆        ┆ s  …      ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [1048]:
# 2. Inconsistencias georáficas: swap lat y long

df2_prim = df2_prim.with_columns(
    latitud = pl.when((pl.col('latitud') <= -6)).then(pl.col('longitud')).otherwise(pl.col('latitud')),
    longitud = pl.when((pl.col('longitud') >= -80)).then(pl.col('latitud')).otherwise(pl.col('longitud'))
)

df2_sec = df2_sec.with_columns(
    latitud = pl.when((pl.col('latitud') <= -6)).then(pl.col('longitud')).otherwise(pl.col('latitud')),
    longitud = pl.when((pl.col('longitud') >= -80)).then(pl.col('latitud')).otherwise(pl.col('longitud'))
)

df2_prim.head()

shape: (5, 12)
┌──────────┬────────┬───────────────┬─────┬───┬────────────┬──────────────┬───────────┬────────────┐
│ CONEXION ┆ SECTOR ┆ CDESTIPSER    ┆ MES ┆ … ┆ fecha_fin  ┆ hora_fin     ┆ latitud   ┆ longitud   │
│ ---      ┆ ---    ┆ ---           ┆ --- ┆   ┆ ---        ┆ ---          ┆ ---       ┆ ---        │
│ i64      ┆ str    ┆ str           ┆ i64 ┆   ┆ date       ┆ datetime[ms] ┆ f64       ┆ f64        │
╞══════════╪════════╪═══════════════╪═════╪═══╪════════════╪══════════════╪═══════════╪════════════╡
│ 4691     ┆ S70    ┆ AG:           ┆ 2   ┆ … ┆ 2025-02-24 ┆ 1899-12-31   ┆ -5.157396 ┆ -80.625483 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 05:36:31.460 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
│ 6234     ┆ S77    ┆ AG:           ┆ 8   ┆ … ┆ 2025-08-28 ┆ 1899-12-31   ┆ -5.187961 ┆ -80.585613 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 08:16:45.482 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
│ 1108     ┆ S80    ┆ AG:           ┆ 10  ┆ … ┆ 2025-10-15 ┆ 1899-12-31   ┆ -5.187178 ┆ -80.626795 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 19:29:16.688 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
│ 2311     ┆ S50    ┆ AG:           ┆ 8   ┆ … ┆ 2025-08-29 ┆ 1899-12-31   ┆ -5.190312 ┆ -80.61709  │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 20:58:00.808 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
│ 3922     ┆ S34    ┆ AG:           ┆ 12  ┆ … ┆ 2025-12-29 ┆ 1899-12-31   ┆ -5.198672 ┆ -80.616827 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 10:23:36.072 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
└──────────┴────────┴───────────────┴─────┴───┴────────────┴──────────────┴───────────┴────────────┘

In [1049]:
df2_prim.describe()

shape: (9, 13)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ CONEXION   ┆ SECTOR ┆ CDESTIPSE ┆ … ┆ fecha_fin ┆ hora_fin  ┆ latitud   ┆ longitud  │
│ ---        ┆ ---        ┆ ---    ┆ R         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ f64        ┆ str    ┆ ---       ┆   ┆ str       ┆ str       ┆ f64       ┆ f64       │
│            ┆            ┆        ┆ str       ┆   ┆           ┆           ┆           ┆           │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 722.0      ┆ 722    ┆ 722       ┆ … ┆ 722       ┆ 722       ┆ 722.0     ┆ 722.0     │
│ null_count ┆ 0.0        ┆ 0      ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 5179.53601 ┆ null   ┆ null      ┆ … ┆ 2025-06-2 ┆ 1899-12-3 ┆ -5.186178 ┆ -80.63369 │
│            ┆ 1          ┆        ┆           ┆   ┆ 6 09:16:2 ┆ 1 12:25:1 ┆           ┆           │
│            ┆            ┆        ┆           ┆   ┆ 7.257617  ┆ 5.874000  ┆           ┆           │
│ std        ┆ 3011.43187 ┆ null   ┆ null      ┆ … ┆ null      ┆ null      ┆ 0.016653  ┆ 0.02801   │
│            ┆ 2          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ min        ┆ 15.0       ┆ S10    ┆ AG: Conex ┆ … ┆ 2025-01-0 ┆ 1899-12-3 ┆ -5.230279 ┆ -80.69132 │
│            ┆            ┆        ┆ iones Dom ┆   ┆ 3         ┆ 1 00:01:5 ┆           ┆ 2         │
│            ┆            ┆        ┆ iciliaria ┆   ┆           ┆ 8.439000  ┆           ┆           │
│            ┆            ┆        ┆ s  …      ┆   ┆           ┆           ┆           ┆           │
│ 25%        ┆ 2557.0     ┆ null   ┆ null      ┆ … ┆ 2025-03-2 ┆ 1899-12-3 ┆ -5.195015 ┆ -80.65591 │
│            ┆            ┆        ┆           ┆   ┆ 0         ┆ 1 06:18:3 ┆           ┆ 4         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 3.302000  ┆           ┆           │
│ 50%        ┆ 5151.0     ┆ null   ┆ null      ┆ … ┆ 2025-06-1 ┆ 1899-12-3 ┆ -5.186394 ┆ -80.63309 │
│            ┆            ┆        ┆           ┆   ┆ 9         ┆ 1 12:52:5 ┆           ┆           │
│            ┆            ┆        ┆           ┆   ┆           ┆ 0.080000  ┆           ┆           │
│ 75%        ┆ 8107.0     ┆ null   ┆ null      ┆ … ┆ 2025-09-2 ┆ 1899-12-3 ┆ -5.176206 ┆ -80.61682 │
│            ┆            ┆        ┆           ┆   ┆ 5         ┆ 1 18:24:5 ┆           ┆ 9         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 4.476000  ┆           ┆           │
│ max        ┆ 10318.0    ┆ S84    ┆ AG: Conex ┆ … ┆ 2026-01-0 ┆ 1899-12-3 ┆ -5.139109 ┆ -80.57538 │
│            ┆            ┆        ┆ iones Dom ┆   ┆ 4         ┆ 1 23:58:4 ┆           ┆ 3         │
│            ┆            ┆        ┆ iciliaria ┆   ┆           ┆ 5.800000  ┆           ┆           │
│            ┆            ┆        ┆ s  …      ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### Reto 2

In [1050]:
# 1. Ranking de roturas y fugas (por sector)

df2_prim = df2_prim.sort(pl.col('SECTOR').count().over('SECTOR'), descending=True)
df2_sec = df2_sec.sort(pl.col('SECTOR').count().over('SECTOR'), descending=True)
df2_prim.head()

shape: (5, 12)
┌──────────┬────────┬───────────────┬─────┬───┬────────────┬──────────────┬───────────┬────────────┐
│ CONEXION ┆ SECTOR ┆ CDESTIPSER    ┆ MES ┆ … ┆ fecha_fin  ┆ hora_fin     ┆ latitud   ┆ longitud   │
│ ---      ┆ ---    ┆ ---           ┆ --- ┆   ┆ ---        ┆ ---          ┆ ---       ┆ ---        │
│ i64      ┆ str    ┆ str           ┆ i64 ┆   ┆ date       ┆ datetime[ms] ┆ f64       ┆ f64        │
╞══════════╪════════╪═══════════════╪═════╪═══╪════════════╪══════════════╪═══════════╪════════════╡
│ 8963     ┆ S84    ┆ AG:           ┆ 6   ┆ … ┆ 2025-06-21 ┆ 1899-12-31   ┆ -5.181692 ┆ -80.651714 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 13:23:14.324 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
│ 8830     ┆ S84    ┆ AG:           ┆ 6   ┆ … ┆ 2025-06-28 ┆ 1899-12-31   ┆ -5.220876 ┆ -80.626795 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 01:53:06.101 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
│ 8845     ┆ S84    ┆ AG:           ┆ 10  ┆ … ┆ 2025-10-22 ┆ 1899-12-31   ┆ -5.195015 ┆ -80.619188 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 20:25:01     ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
│ 9050     ┆ S84    ┆ AG:           ┆ 12  ┆ … ┆ 2025-12-23 ┆ 1899-12-31   ┆ -5.173594 ┆ -80.610535 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 18:19:55.792 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
│ 9136     ┆ S84    ┆ AG:           ┆ 9   ┆ … ┆ 2025-09-20 ┆ 1899-12-31   ┆ -5.186916 ┆ -80.580891 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 07:28:02.820 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
└──────────┴────────┴───────────────┴─────┴───┴────────────┴──────────────┴───────────┴────────────┘

In [1051]:
# 2. Cálculo de tiempo de reparación promedio

df2_prim = df2_prim.with_columns(
    datetime_inicio = pl.col('fecha_inicio').dt.combine(pl.col('hora_inicio').dt.time()),
    datetime_fin = pl.col('fecha_fin').dt.combine(pl.col('hora_fin').dt.time()),
)
df2_prim = df2_prim.with_columns(
    duracion = pl.col('datetime_fin') - pl.col('datetime_inicio')
)


df2_prim.head()

shape: (5, 15)
┌──────────┬────────┬─────────────┬─────┬───┬────────────┬─────────────┬─────────────┬─────────────┐
│ CONEXION ┆ SECTOR ┆ CDESTIPSER  ┆ MES ┆ … ┆ longitud   ┆ datetime_in ┆ datetime_fi ┆ duracion    │
│ ---      ┆ ---    ┆ ---         ┆ --- ┆   ┆ ---        ┆ icio        ┆ n           ┆ ---         │
│ i64      ┆ str    ┆ str         ┆ i64 ┆   ┆ f64        ┆ ---         ┆ ---         ┆ duration[μs │
│          ┆        ┆             ┆     ┆   ┆            ┆ datetime[μs ┆ datetime[μs ┆ ]           │
│          ┆        ┆             ┆     ┆   ┆            ┆ ]           ┆ ]           ┆             │
╞══════════╪════════╪═════════════╪═════╪═══╪════════════╪═════════════╪═════════════╪═════════════╡
│ 8963     ┆ S84    ┆ AG:         ┆ 6   ┆ … ┆ -80.651714 ┆ 2025-06-18  ┆ 2025-06-21  ┆ 3d 8h 22m   │
│          ┆        ┆ Conexiones  ┆     ┆   ┆            ┆ 05:01:00    ┆ 13:23:14.32 ┆ 14s 324ms   │
│          ┆        ┆ Domiciliari ┆     ┆   ┆            ┆             ┆ 4           ┆             │
│          ┆        ┆ as  …       ┆     ┆   ┆            ┆             ┆             ┆             │
│ 8830     ┆ S84    ┆ AG:         ┆ 6   ┆ … ┆ -80.626795 ┆ 2025-06-25  ┆ 2025-06-28  ┆ 2d 4h 52m   │
│          ┆        ┆ Conexiones  ┆     ┆   ┆            ┆ 21:01:00    ┆ 01:53:06.10 ┆ 6s 101ms    │
│          ┆        ┆ Domiciliari ┆     ┆   ┆            ┆             ┆ 1           ┆             │
│          ┆        ┆ as  …       ┆     ┆   ┆            ┆             ┆             ┆             │
│ 8845     ┆ S84    ┆ AG:         ┆ 10  ┆ … ┆ -80.619188 ┆ 2025-10-21  ┆ 2025-10-22  ┆ 1d 20h 24m  │
│          ┆        ┆ Conexiones  ┆     ┆   ┆            ┆ 00:01:00    ┆ 20:25:01    ┆ 1s          │
│          ┆        ┆ Domiciliari ┆     ┆   ┆            ┆             ┆             ┆             │
│          ┆        ┆ as  …       ┆     ┆   ┆            ┆             ┆             ┆             │
│ 9050     ┆ S84    ┆ AG:         ┆ 12  ┆ … ┆ -80.610535 ┆ 2025-12-20  ┆ 2025-12-23  ┆ 3d 4h 18m   │
│          ┆        ┆ Conexiones  ┆     ┆   ┆            ┆ 14:01:00    ┆ 18:19:55.79 ┆ 55s 792ms   │
│          ┆        ┆ Domiciliari ┆     ┆   ┆            ┆             ┆ 2           ┆             │
│          ┆        ┆ as  …       ┆     ┆   ┆            ┆             ┆             ┆             │
│ 9136     ┆ S84    ┆ AG:         ┆ 9   ┆ … ┆ -80.580891 ┆ 2025-09-17  ┆ 2025-09-20  ┆ 2d 8h 27m   │
│          ┆        ┆ Conexiones  ┆     ┆   ┆            ┆ 23:01:00    ┆ 07:28:02.82 ┆ 2s 820ms    │
│          ┆        ┆ Domiciliari ┆     ┆   ┆            ┆             ┆ 0           ┆             │
│          ┆        ┆ as  …       ┆     ┆   ┆            ┆             ┆             ┆             │
└──────────┴────────┴─────────────┴─────┴───┴────────────┴─────────────┴─────────────┴─────────────┘

In [1052]:
df2_sec = df2_sec.with_columns(
    datetime_inicio = pl.col('fecha_inicio').dt.combine(pl.col('hora_inicio').dt.time()),
    datetime_fin = pl.col('fecha_fin').dt.combine(pl.col('hora_fin').dt.time()),
)
df2_sec = df2_sec.with_columns(
    duracion = pl.col('datetime_fin') - pl.col('datetime_inicio')
)

df2_sec.head()

shape: (5, 15)
┌──────────┬────────┬─────────────┬─────┬───┬────────────┬─────────────┬─────────────┬─────────────┐
│ CONEXION ┆ SECTOR ┆ CDESTIPSER  ┆ MES ┆ … ┆ longitud   ┆ datetime_in ┆ datetime_fi ┆ duracion    │
│ ---      ┆ ---    ┆ ---         ┆ --- ┆   ┆ ---        ┆ icio        ┆ n           ┆ ---         │
│ i64      ┆ str    ┆ str         ┆ i64 ┆   ┆ f64        ┆ ---         ┆ ---         ┆ duration[μs │
│          ┆        ┆             ┆     ┆   ┆            ┆ datetime[μs ┆ datetime[μs ┆ ]           │
│          ┆        ┆             ┆     ┆   ┆            ┆ ]           ┆ ]           ┆             │
╞══════════╪════════╪═════════════╪═════╪═══╪════════════╪═════════════╪═════════════╪═════════════╡
│ 8826     ┆ S84    ┆ AG:         ┆ 12  ┆ … ┆ -80.592695 ┆ 2025-12-01  ┆ 2025-12-03  ┆ 1d 10h 43m  │
│          ┆        ┆ Conexiones  ┆     ┆   ┆            ┆ 21:05:00    ┆ 07:48:39.00 ┆ 39s 4ms     │
│          ┆        ┆ Domiciliari ┆     ┆   ┆            ┆             ┆ 4           ┆             │
│          ┆        ┆ as  …       ┆     ┆   ┆            ┆             ┆             ┆             │
│ 8697     ┆ S84    ┆ AG:         ┆ 3   ┆ … ┆ -80.608433 ┆ 2025-03-26  ┆ 2025-03-27  ┆ 20h 5m 45s  │
│          ┆        ┆ Conexiones  ┆     ┆   ┆            ┆ 19:18:00    ┆ 15:23:45.12 ┆ 120ms       │
│          ┆        ┆ Domiciliari ┆     ┆   ┆            ┆             ┆ 0           ┆             │
│          ┆        ┆ as  …       ┆     ┆   ┆            ┆             ┆             ┆             │
│ 9172     ┆ S84    ┆ AG:         ┆ 3   ┆ … ┆ -80.62968  ┆ 2025-03-31  ┆ 2025-04-01  ┆ 1d 7h 57m   │
│          ┆        ┆ Conexiones  ┆     ┆   ┆            ┆ 08:09:00    ┆ 16:06:04.85 ┆ 4s 852ms    │
│          ┆        ┆ Domiciliari ┆     ┆   ┆            ┆             ┆ 2           ┆             │
│          ┆        ┆ as  …       ┆     ┆   ┆            ┆             ┆             ┆             │
│ 8847     ┆ S84    ┆ AG:         ┆ 3   ┆ … ┆ -80.638596 ┆ 2025-03-10  ┆ 2025-03-10  ┆ 6h 46m 31s  │
│          ┆        ┆ Conexiones  ┆     ┆   ┆            ┆ 14:13:00    ┆ 20:59:31.72 ┆ 720ms       │
│          ┆        ┆ Domiciliari ┆     ┆   ┆            ┆             ┆ 0           ┆             │
│          ┆        ┆ as  …       ┆     ┆   ┆            ┆             ┆             ┆             │
│ 8799     ┆ S84    ┆ AG:         ┆ 2   ┆ … ┆ -80.599515 ┆ 2025-02-08  ┆ 2025-02-09  ┆ 20h 54m 58s │
│          ┆        ┆ Conexiones  ┆     ┆   ┆            ┆ 03:35:00    ┆ 00:29:58.79 ┆ 796ms       │
│          ┆        ┆ Domiciliari ┆     ┆   ┆            ┆             ┆ 6           ┆             │
│          ┆        ┆ as  …       ┆     ┆   ┆            ┆             ┆             ┆             │
└──────────┴────────┴─────────────┴─────┴───┴────────────┴─────────────┴─────────────┴─────────────┘