### Obtain

In [111]:
import polars as pl
import numpy as np

# set random seed for reproducibility
np.random.seed(42)

df_02 = pl.read_excel('datasets/02_ROTURAS_RED_PRIMARIA_SECUNDARIA_PIURA.xlsx')

df_02.head()

shape: (5, 12)
┌──────────┬────────┬──────────────┬─────┬───┬────────────┬──────────────┬────────────┬────────────┐
│ CONEXION ┆ SECTOR ┆ CDESTIPSER   ┆ MES ┆ … ┆ fecha_fin  ┆ hora_fin     ┆ latitud    ┆ longitud   │
│ ---      ┆ ---    ┆ ---          ┆ --- ┆   ┆ ---        ┆ ---          ┆ ---        ┆ ---        │
│ i64      ┆ str    ┆ str          ┆ i64 ┆   ┆ date       ┆ datetime[ms] ┆ f64        ┆ f64        │
╞══════════╪════════╪══════════════╪═════╪═══╪════════════╪══════════════╪════════════╪════════════╡
│ 15       ┆ S74    ┆ AG:          ┆ 7   ┆ … ┆ 2025-07-14 ┆ 1899-12-31   ┆ -5.222965  ┆ -80.627582 │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 09:59:24.144 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
│ 17       ┆ S74    ┆ AG:          ┆ 6   ┆ … ┆ 2025-06-04 ┆ 1899-12-31   ┆ -5.16027   ┆ -80.631254 │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 05:13:25.844 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
│ 18       ┆ S74    ┆ AG:          ┆ 10  ┆ … ┆ 2025-10-15 ┆ 1899-12-31   ┆ -5.188223  ┆ -80.622336 │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 11:58:01.844 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
│ 23       ┆ S74    ┆ AG:          ┆ 1   ┆ … ┆ 2025-01-15 ┆ 1899-12-31   ┆ -5.197104  ┆ -80.587974 │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 16:03:23.544 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
│ 32       ┆ S74    ┆ AG:          ┆ 12  ┆ … ┆ 2025-12-24 ┆ 1899-12-31   ┆ -80.619972 ┆ -5.224533  │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 00:48:45.822 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
└──────────┴────────┴──────────────┴─────┴───┴────────────┴──────────────┴────────────┴────────────┘

In [112]:
df_02.describe()

shape: (9, 13)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ CONEXION   ┆ SECTOR ┆ CDESTIPSE ┆ … ┆ fecha_fin ┆ hora_fin  ┆ latitud   ┆ longitud  │
│ ---        ┆ ---        ┆ ---    ┆ R         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ f64        ┆ str    ┆ ---       ┆   ┆ str       ┆ str       ┆ f64       ┆ f64       │
│            ┆            ┆        ┆ str       ┆   ┆           ┆           ┆           ┆           │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 726.0      ┆ 726    ┆ 726       ┆ … ┆ 726       ┆ 726       ┆ 726.0     ┆ 726.0     │
│ null_count ┆ 0.0        ┆ 0      ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 5183.84022 ┆ null   ┆ null      ┆ … ┆ 2025-06-2 ┆ 1899-12-3 ┆ -12.77289 ┆ -73.04698 │
│            ┆            ┆        ┆           ┆   ┆ 6 02:54:3 ┆ 1 12:24:4 ┆ 1         ┆ 1         │
│            ┆            ┆        ┆           ┆   ┆ 2.727272  ┆ 7.341000  ┆           ┆           │
│ std        ┆ 3008.16745 ┆ null   ┆ null      ┆ … ┆ null      ┆ null      ┆ 22.705702 ┆ 22.70561  │
│            ┆ 3          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ min        ┆ 15.0       ┆ S10    ┆ AG: Conex ┆ … ┆ 2025-01-0 ┆ 1899-12-3 ┆ -80.68765 ┆ -80.69132 │
│            ┆            ┆        ┆ iones Dom ┆   ┆ 3         ┆ 1 00:01:5 ┆ 3         ┆ 2         │
│            ┆            ┆        ┆ iciliaria ┆   ┆           ┆ 8.439000  ┆           ┆           │
│            ┆            ┆        ┆ s  …      ┆   ┆           ┆           ┆           ┆           │
│ 25%        ┆ 2562.0     ┆ null   ┆ null      ┆ … ┆ 2025-03-2 ┆ 1899-12-3 ┆ -5.199978 ┆ -80.65302 │
│            ┆            ┆        ┆           ┆   ┆ 0         ┆ 1 06:18:3 ┆           ┆ 6         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 3.302000  ┆           ┆           │
│ 50%        ┆ 5155.0     ┆ null   ┆ null      ┆ … ┆ 2025-06-1 ┆ 1899-12-3 ┆ -5.188223 ┆ -80.62968 │
│            ┆            ┆        ┆           ┆   ┆ 9         ┆ 1 12:52:5 ┆           ┆           │
│            ┆            ┆        ┆           ┆   ┆           ┆ 0.080000  ┆           ┆           │
│ 75%        ┆ 8107.0     ┆ null   ┆ null      ┆ … ┆ 2025-09-2 ┆ 1899-12-3 ┆ -5.177773 ┆ -80.59925 │
│            ┆            ┆        ┆           ┆   ┆ 5         ┆ 1 18:24:1 ┆           ┆ 3         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 6.688000  ┆           ┆           │
│ max        ┆ 10318.0    ┆ S84    ┆ AG: Conex ┆ … ┆ 2026-01-0 ┆ 1899-12-3 ┆ -5.139109 ┆ -5.143028 │
│            ┆            ┆        ┆ iones Dom ┆   ┆ 4         ┆ 1 23:58:4 ┆           ┆           │
│            ┆            ┆        ┆ iciliaria ┆   ┆           ┆ 5.800000  ┆           ┆           │
│            ┆            ┆        ┆ s  …      ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### Scrub

In [113]:
# Reto 1:
# 1. Remover duplicados

df_02 = df_02.unique(subset=['SECTOR', 'fecha_inicio'], keep='first')
df_02.head()

shape: (5, 12)
┌──────────┬────────┬───────────────┬─────┬───┬────────────┬──────────────┬───────────┬────────────┐
│ CONEXION ┆ SECTOR ┆ CDESTIPSER    ┆ MES ┆ … ┆ fecha_fin  ┆ hora_fin     ┆ latitud   ┆ longitud   │
│ ---      ┆ ---    ┆ ---           ┆ --- ┆   ┆ ---        ┆ ---          ┆ ---       ┆ ---        │
│ i64      ┆ str    ┆ str           ┆ i64 ┆   ┆ date       ┆ datetime[ms] ┆ f64       ┆ f64        │
╞══════════╪════════╪═══════════════╪═════╪═══╪════════════╪══════════════╪═══════════╪════════════╡
│ 9397     ┆ S22    ┆ AG:           ┆ 11  ┆ … ┆ 2025-11-19 ┆ 1899-12-31   ┆ -5.181692 ┆ -80.623123 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 13:13:36.164 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
│ 9351     ┆ S25    ┆ AG:           ┆ 6   ┆ … ┆ 2025-06-06 ┆ 1899-12-31   ┆ -5.192141 ┆ -80.603187 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 16:09:31.924 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
│ 8111     ┆ S51    ┆ AG:           ┆ 1   ┆ … ┆ 2025-01-22 ┆ 1899-12-31   ┆ -5.158441 ┆ -80.663255 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 03:23:11.058 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
│ 2065     ┆ S66    ┆ AG:           ┆ 3   ┆ … ┆ 2025-03-10 ┆ 1899-12-31   ┆ -5.195276 ┆ -80.643058 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 03:01:04.338 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
│ 1924     ┆ S66    ┆ AG:           ┆ 8   ┆ … ┆ 2025-08-30 ┆ 1899-12-31   ┆ -5.180908 ┆ -80.586662 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 20:44:19.272 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
└──────────┴────────┴───────────────┴─────┴───┴────────────┴──────────────┴───────────┴────────────┘

In [114]:
df_02.describe()

shape: (9, 13)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ CONEXION   ┆ SECTOR ┆ CDESTIPSE ┆ … ┆ fecha_fin ┆ hora_fin  ┆ latitud   ┆ longitud  │
│ ---        ┆ ---        ┆ ---    ┆ R         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ f64        ┆ str    ┆ ---       ┆   ┆ str       ┆ str       ┆ f64       ┆ f64       │
│            ┆            ┆        ┆ str       ┆   ┆           ┆           ┆           ┆           │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 677.0      ┆ 677    ┆ 677       ┆ … ┆ 677       ┆ 677       ┆ 677.0     ┆ 677.0     │
│ null_count ┆ 0.0        ┆ 0      ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 5190.22452 ┆ null   ┆ null      ┆ … ┆ 2025-06-2 ┆ 1899-12-3 ┆ -12.65305 ┆ -73.16645 │
│            ┆            ┆        ┆           ┆   ┆ 8 10:50:5 ┆ 1 12:19:2 ┆ 3         ┆ 3         │
│            ┆            ┆        ┆           ┆   ┆ 2.289512  ┆ 0.175000  ┆           ┆           │
│ std        ┆ 3011.18171 ┆ null   ┆ null      ┆ … ┆ null      ┆ null      ┆ 22.546626 ┆ 22.546909 │
│            ┆ 3          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ min        ┆ 15.0       ┆ S10    ┆ AG: Conex ┆ … ┆ 2025-01-0 ┆ 1899-12-3 ┆ -80.68765 ┆ -80.69132 │
│            ┆            ┆        ┆ iones Dom ┆   ┆ 3         ┆ 1 00:01:5 ┆ 3         ┆ 2         │
│            ┆            ┆        ┆ iciliaria ┆   ┆           ┆ 8.439000  ┆           ┆           │
│            ┆            ┆        ┆ s  …      ┆   ┆           ┆           ┆           ┆           │
│ 25%        ┆ 2562.0     ┆ null   ┆ null      ┆ … ┆ 2025-03-2 ┆ 1899-12-3 ┆ -5.199455 ┆ -80.65355 │
│            ┆            ┆        ┆           ┆   ┆ 2         ┆ 1 06:14:1 ┆           ┆           │
│            ┆            ┆        ┆           ┆   ┆           ┆ 0.534000  ┆           ┆           │
│ 50%        ┆ 5159.0     ┆ null   ┆ null      ┆ … ┆ 2025-06-2 ┆ 1899-12-3 ┆ -5.188223 ┆ -80.62968 │
│            ┆            ┆        ┆           ┆   ┆ 3         ┆ 1 12:40:4 ┆           ┆           │
│            ┆            ┆        ┆           ┆   ┆           ┆ 0.928000  ┆           ┆           │
│ 75%        ┆ 8132.0     ┆ null   ┆ null      ┆ … ┆ 2025-09-2 ┆ 1899-12-3 ┆ -5.177773 ┆ -80.59872 │
│            ┆            ┆        ┆           ┆   ┆ 9         ┆ 1 18:24:1 ┆           ┆ 8         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 6.688000  ┆           ┆           │
│ max        ┆ 10318.0    ┆ S84    ┆ AG: Conex ┆ … ┆ 2026-01-0 ┆ 1899-12-3 ┆ -5.139109 ┆ -5.143028 │
│            ┆            ┆        ┆ iones Dom ┆   ┆ 4         ┆ 1 23:58:4 ┆           ┆           │
│            ┆            ┆        ┆ iciliaria ┆   ┆           ┆ 5.800000  ┆           ┆           │
│            ┆            ┆        ┆ s  …      ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [115]:
# 2. Inconsistencias gráficas: switch lat y long

#mal_coords = pl.when()

df_02 = df_02.with_columns(
    pl.when((pl.col('latitud') <= -6) | (pl.col('longitud') >= -82)).then(pl.col('longitud')).otherwise(pl.col('latitud')),
    pl.when((pl.col('latitud') <= -6) | (pl.col('longitud') >= -82)).then(pl.col('latitud')).otherwise(pl.col('longitud'))
)

df_02.unique()
df_02.head()

shape: (5, 12)
┌──────────┬────────┬───────────────┬─────┬───┬────────────┬──────────────┬───────────┬────────────┐
│ CONEXION ┆ SECTOR ┆ CDESTIPSER    ┆ MES ┆ … ┆ fecha_fin  ┆ hora_fin     ┆ latitud   ┆ longitud   │
│ ---      ┆ ---    ┆ ---           ┆ --- ┆   ┆ ---        ┆ ---          ┆ ---       ┆ ---        │
│ i64      ┆ str    ┆ str           ┆ i64 ┆   ┆ date       ┆ datetime[ms] ┆ f64       ┆ f64        │
╞══════════╪════════╪═══════════════╪═════╪═══╪════════════╪══════════════╪═══════════╪════════════╡
│ 9397     ┆ S22    ┆ AG:           ┆ 11  ┆ … ┆ 2025-11-19 ┆ 1899-12-31   ┆ -5.181692 ┆ -80.623123 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 13:13:36.164 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
│ 9351     ┆ S25    ┆ AG:           ┆ 6   ┆ … ┆ 2025-06-06 ┆ 1899-12-31   ┆ -5.192141 ┆ -80.603187 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 16:09:31.924 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
│ 8111     ┆ S51    ┆ AG:           ┆ 1   ┆ … ┆ 2025-01-22 ┆ 1899-12-31   ┆ -5.158441 ┆ -80.663255 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 03:23:11.058 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
│ 2065     ┆ S66    ┆ AG:           ┆ 3   ┆ … ┆ 2025-03-10 ┆ 1899-12-31   ┆ -5.195276 ┆ -80.643058 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 03:01:04.338 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
│ 1924     ┆ S66    ┆ AG:           ┆ 8   ┆ … ┆ 2025-08-30 ┆ 1899-12-31   ┆ -5.180908 ┆ -80.586662 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 20:44:19.272 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
└──────────┴────────┴───────────────┴─────┴───┴────────────┴──────────────┴───────────┴────────────┘

In [116]:
df_02.describe()

shape: (9, 13)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ CONEXION   ┆ SECTOR ┆ CDESTIPSE ┆ … ┆ fecha_fin ┆ hora_fin  ┆ latitud   ┆ longitud  │
│ ---        ┆ ---        ┆ ---    ┆ R         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ f64        ┆ str    ┆ ---       ┆   ┆ str       ┆ str       ┆ f64       ┆ f64       │
│            ┆            ┆        ┆ str       ┆   ┆           ┆           ┆           ┆           │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 677.0      ┆ 677    ┆ 677       ┆ … ┆ 677       ┆ 677       ┆ 677.0     ┆ 677.0     │
│ null_count ┆ 0.0        ┆ 0      ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 5190.22452 ┆ null   ┆ null      ┆ … ┆ 2025-06-2 ┆ 1899-12-3 ┆ -12.65305 ┆ -73.16645 │
│            ┆            ┆        ┆           ┆   ┆ 8 10:50:5 ┆ 1 12:19:2 ┆ 3         ┆ 3         │
│            ┆            ┆        ┆           ┆   ┆ 2.289512  ┆ 0.175000  ┆           ┆           │
│ std        ┆ 3011.18171 ┆ null   ┆ null      ┆ … ┆ null      ┆ null      ┆ 22.546626 ┆ 22.546909 │
│            ┆ 3          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ min        ┆ 15.0       ┆ S10    ┆ AG: Conex ┆ … ┆ 2025-01-0 ┆ 1899-12-3 ┆ -80.68765 ┆ -80.69132 │
│            ┆            ┆        ┆ iones Dom ┆   ┆ 3         ┆ 1 00:01:5 ┆ 3         ┆ 2         │
│            ┆            ┆        ┆ iciliaria ┆   ┆           ┆ 8.439000  ┆           ┆           │
│            ┆            ┆        ┆ s  …      ┆   ┆           ┆           ┆           ┆           │
│ 25%        ┆ 2562.0     ┆ null   ┆ null      ┆ … ┆ 2025-03-2 ┆ 1899-12-3 ┆ -5.199455 ┆ -80.65355 │
│            ┆            ┆        ┆           ┆   ┆ 2         ┆ 1 06:14:1 ┆           ┆           │
│            ┆            ┆        ┆           ┆   ┆           ┆ 0.534000  ┆           ┆           │
│ 50%        ┆ 5159.0     ┆ null   ┆ null      ┆ … ┆ 2025-06-2 ┆ 1899-12-3 ┆ -5.188223 ┆ -80.62968 │
│            ┆            ┆        ┆           ┆   ┆ 3         ┆ 1 12:40:4 ┆           ┆           │
│            ┆            ┆        ┆           ┆   ┆           ┆ 0.928000  ┆           ┆           │
│ 75%        ┆ 8132.0     ┆ null   ┆ null      ┆ … ┆ 2025-09-2 ┆ 1899-12-3 ┆ -5.177773 ┆ -80.59872 │
│            ┆            ┆        ┆           ┆   ┆ 9         ┆ 1 18:24:1 ┆           ┆ 8         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 6.688000  ┆           ┆           │
│ max        ┆ 10318.0    ┆ S84    ┆ AG: Conex ┆ … ┆ 2026-01-0 ┆ 1899-12-3 ┆ -5.139109 ┆ -5.143028 │
│            ┆            ┆        ┆ iones Dom ┆   ┆ 4         ┆ 1 23:58:4 ┆           ┆           │
│            ┆            ┆        ┆ iciliaria ┆   ┆           ┆ 5.800000  ┆           ┆           │
│            ┆            ┆        ┆ s  …      ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### Reto 2

In [117]:
# 1. Ranking de roturas y fugas (por sector)

#df_02_ordered = df_02.with_columns(group_count=pl.col('SECTOR').count().over('SECTOR')).sort('group_count', descending=True)
df_02_ordered = df_02.sort(pl.col('SECTOR').count().over('SECTOR'), descending=True)
df_02_ordered.head()

shape: (5, 12)
┌──────────┬────────┬──────────────┬─────┬───┬────────────┬──────────────┬────────────┬────────────┐
│ CONEXION ┆ SECTOR ┆ CDESTIPSER   ┆ MES ┆ … ┆ fecha_fin  ┆ hora_fin     ┆ latitud    ┆ longitud   │
│ ---      ┆ ---    ┆ ---          ┆ --- ┆   ┆ ---        ┆ ---          ┆ ---        ┆ ---        │
│ i64      ┆ str    ┆ str          ┆ i64 ┆   ┆ date       ┆ datetime[ms] ┆ f64        ┆ f64        │
╞══════════╪════════╪══════════════╪═════╪═══╪════════════╪══════════════╪════════════╪════════════╡
│ 8740     ┆ S84    ┆ AG:          ┆ 2   ┆ … ┆ 2025-02-19 ┆ 1899-12-31   ┆ -80.672173 ┆ -5.163928  │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 04:36:18.191 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
│ 8963     ┆ S84    ┆ AG:          ┆ 6   ┆ … ┆ 2025-06-21 ┆ 1899-12-31   ┆ -5.181692  ┆ -80.651714 │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 13:23:14.324 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
│ 8699     ┆ S84    ┆ AG:          ┆ 9   ┆ … ┆ 2025-09-23 ┆ 1899-12-31   ┆ -5.225839  ┆ -80.615253 │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 01:22:47.987 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
│ 8891     ┆ S84    ┆ AG:          ┆ 1   ┆ … ┆ 2025-02-03 ┆ 1899-12-31   ┆ -5.17281   ┆ -80.651452 │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 13:52:22.552 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
│ 9058     ┆ S84    ┆ AG:          ┆ 12  ┆ … ┆ 2025-12-14 ┆ 1899-12-31   ┆ -5.185349  ┆ -80.652763 │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 02:35:01.011 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
└──────────┴────────┴──────────────┴─────┴───┴────────────┴──────────────┴────────────┴────────────┘