### Obtain

In [125]:
import polars as pl
import numpy as np

# set random seed for reproducibility
np.random.seed(42)

df_02 = pl.read_excel('datasets/02_ROTURAS_RED_PRIMARIA_SECUNDARIA_PIURA.xlsx')

df_02.head()

shape: (5, 12)
┌──────────┬────────┬──────────────┬─────┬───┬────────────┬──────────────┬────────────┬────────────┐
│ CONEXION ┆ SECTOR ┆ CDESTIPSER   ┆ MES ┆ … ┆ fecha_fin  ┆ hora_fin     ┆ latitud    ┆ longitud   │
│ ---      ┆ ---    ┆ ---          ┆ --- ┆   ┆ ---        ┆ ---          ┆ ---        ┆ ---        │
│ i64      ┆ str    ┆ str          ┆ i64 ┆   ┆ date       ┆ datetime[ms] ┆ f64        ┆ f64        │
╞══════════╪════════╪══════════════╪═════╪═══╪════════════╪══════════════╪════════════╪════════════╡
│ 15       ┆ S74    ┆ AG:          ┆ 7   ┆ … ┆ 2025-07-14 ┆ 1899-12-31   ┆ -5.222965  ┆ -80.627582 │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 09:59:24.144 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
│ 17       ┆ S74    ┆ AG:          ┆ 6   ┆ … ┆ 2025-06-04 ┆ 1899-12-31   ┆ -5.16027   ┆ -80.631254 │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 05:13:25.844 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
│ 18       ┆ S74    ┆ AG:          ┆ 10  ┆ … ┆ 2025-10-15 ┆ 1899-12-31   ┆ -5.188223  ┆ -80.622336 │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 11:58:01.844 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
│ 23       ┆ S74    ┆ AG:          ┆ 1   ┆ … ┆ 2025-01-15 ┆ 1899-12-31   ┆ -5.197104  ┆ -80.587974 │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 16:03:23.544 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
│ 32       ┆ S74    ┆ AG:          ┆ 12  ┆ … ┆ 2025-12-24 ┆ 1899-12-31   ┆ -80.619972 ┆ -5.224533  │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 00:48:45.822 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
└──────────┴────────┴──────────────┴─────┴───┴────────────┴──────────────┴────────────┴────────────┘

In [126]:
df_02.describe()

shape: (9, 13)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ CONEXION   ┆ SECTOR ┆ CDESTIPSE ┆ … ┆ fecha_fin ┆ hora_fin  ┆ latitud   ┆ longitud  │
│ ---        ┆ ---        ┆ ---    ┆ R         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ f64        ┆ str    ┆ ---       ┆   ┆ str       ┆ str       ┆ f64       ┆ f64       │
│            ┆            ┆        ┆ str       ┆   ┆           ┆           ┆           ┆           │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 726.0      ┆ 726    ┆ 726       ┆ … ┆ 726       ┆ 726       ┆ 726.0     ┆ 726.0     │
│ null_count ┆ 0.0        ┆ 0      ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 5183.84022 ┆ null   ┆ null      ┆ … ┆ 2025-06-2 ┆ 1899-12-3 ┆ -12.77289 ┆ -73.04698 │
│            ┆            ┆        ┆           ┆   ┆ 6 02:54:3 ┆ 1 12:24:4 ┆ 1         ┆ 1         │
│            ┆            ┆        ┆           ┆   ┆ 2.727272  ┆ 7.341000  ┆           ┆           │
│ std        ┆ 3008.16745 ┆ null   ┆ null      ┆ … ┆ null      ┆ null      ┆ 22.705702 ┆ 22.70561  │
│            ┆ 3          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ min        ┆ 15.0       ┆ S10    ┆ AG: Conex ┆ … ┆ 2025-01-0 ┆ 1899-12-3 ┆ -80.68765 ┆ -80.69132 │
│            ┆            ┆        ┆ iones Dom ┆   ┆ 3         ┆ 1 00:01:5 ┆ 3         ┆ 2         │
│            ┆            ┆        ┆ iciliaria ┆   ┆           ┆ 8.439000  ┆           ┆           │
│            ┆            ┆        ┆ s  …      ┆   ┆           ┆           ┆           ┆           │
│ 25%        ┆ 2562.0     ┆ null   ┆ null      ┆ … ┆ 2025-03-2 ┆ 1899-12-3 ┆ -5.199978 ┆ -80.65302 │
│            ┆            ┆        ┆           ┆   ┆ 0         ┆ 1 06:18:3 ┆           ┆ 6         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 3.302000  ┆           ┆           │
│ 50%        ┆ 5155.0     ┆ null   ┆ null      ┆ … ┆ 2025-06-1 ┆ 1899-12-3 ┆ -5.188223 ┆ -80.62968 │
│            ┆            ┆        ┆           ┆   ┆ 9         ┆ 1 12:52:5 ┆           ┆           │
│            ┆            ┆        ┆           ┆   ┆           ┆ 0.080000  ┆           ┆           │
│ 75%        ┆ 8107.0     ┆ null   ┆ null      ┆ … ┆ 2025-09-2 ┆ 1899-12-3 ┆ -5.177773 ┆ -80.59925 │
│            ┆            ┆        ┆           ┆   ┆ 5         ┆ 1 18:24:1 ┆           ┆ 3         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 6.688000  ┆           ┆           │
│ max        ┆ 10318.0    ┆ S84    ┆ AG: Conex ┆ … ┆ 2026-01-0 ┆ 1899-12-3 ┆ -5.139109 ┆ -5.143028 │
│            ┆            ┆        ┆ iones Dom ┆   ┆ 4         ┆ 1 23:58:4 ┆           ┆           │
│            ┆            ┆        ┆ iciliaria ┆   ┆           ┆ 5.800000  ┆           ┆           │
│            ┆            ┆        ┆ s  …      ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### Retos

In [127]:
# Reto 1:
# 1. Remover duplicados

df_02 = df_02.unique(subset=['CONEXION', 'CATEGORIA', 'fecha_inicio'], keep='first')
df_02.head()

shape: (5, 12)
┌──────────┬────────┬───────────────┬─────┬───┬────────────┬──────────────┬───────────┬────────────┐
│ CONEXION ┆ SECTOR ┆ CDESTIPSER    ┆ MES ┆ … ┆ fecha_fin  ┆ hora_fin     ┆ latitud   ┆ longitud   │
│ ---      ┆ ---    ┆ ---           ┆ --- ┆   ┆ ---        ┆ ---          ┆ ---       ┆ ---        │
│ i64      ┆ str    ┆ str           ┆ i64 ┆   ┆ date       ┆ datetime[ms] ┆ f64       ┆ f64        │
╞══════════╪════════╪═══════════════╪═════╪═══╪════════════╪══════════════╪═══════════╪════════════╡
│ 3776     ┆ S75    ┆ AG:           ┆ 1   ┆ … ┆ 2025-02-02 ┆ 1899-12-31   ┆ -5.187439 ┆ -80.626533 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 09:42:52.760 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
│ 1241     ┆ S80    ┆ AG:           ┆ 6   ┆ … ┆ 2025-06-21 ┆ 1899-12-31   ┆ -5.197627 ┆ -80.659583 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 05:50:08.284 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
│ 4080     ┆ S67    ┆ AG:           ┆ 10  ┆ … ┆ 2025-10-08 ┆ 1899-12-31   ┆ -5.178034 ┆ -80.590859 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 19:08:12.560 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
│ 3209     ┆ S35    ┆ AG:           ┆ 2   ┆ … ┆ 2025-02-17 ┆ 1899-12-31   ┆ -5.194231 ┆ -80.666403 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 07:53:54.632 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
│ 7756     ┆ S83    ┆ AG:           ┆ 6   ┆ … ┆ 2025-06-07 ┆ 1899-12-31   ┆ -5.165495 ┆ -80.647779 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 21:29:58.176 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
└──────────┴────────┴───────────────┴─────┴───┴────────────┴──────────────┴───────────┴────────────┘

In [128]:
df_02.describe()

shape: (9, 13)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ CONEXION   ┆ SECTOR ┆ CDESTIPSE ┆ … ┆ fecha_fin ┆ hora_fin  ┆ latitud   ┆ longitud  │
│ ---        ┆ ---        ┆ ---    ┆ R         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ f64        ┆ str    ┆ ---       ┆   ┆ str       ┆ str       ┆ f64       ┆ f64       │
│            ┆            ┆        ┆ str       ┆   ┆           ┆           ┆           ┆           │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 722.0      ┆ 722    ┆ 722       ┆ … ┆ 722       ┆ 722       ┆ 722.0     ┆ 722.0     │
│ null_count ┆ 0.0        ┆ 0      ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 5179.53601 ┆ null   ┆ null      ┆ … ┆ 2025-06-2 ┆ 1899-12-3 ┆ -12.71039 ┆ -73.10947 │
│            ┆ 1          ┆        ┆           ┆   ┆ 6 09:16:2 ┆ 1 12:25:1 ┆ 2         ┆ 6         │
│            ┆            ┆        ┆           ┆   ┆ 7.257617  ┆ 5.874000  ┆           ┆           │
│ std        ┆ 3011.43187 ┆ null   ┆ null      ┆ … ┆ null      ┆ null      ┆ 22.62264  ┆ 22.622416 │
│            ┆ 2          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ min        ┆ 15.0       ┆ S10    ┆ AG: Conex ┆ … ┆ 2025-01-0 ┆ 1899-12-3 ┆ -80.68765 ┆ -80.69132 │
│            ┆            ┆        ┆ iones Dom ┆   ┆ 3         ┆ 1 00:01:5 ┆ 3         ┆ 2         │
│            ┆            ┆        ┆ iciliaria ┆   ┆           ┆ 8.439000  ┆           ┆           │
│            ┆            ┆        ┆ s  …      ┆   ┆           ┆           ┆           ┆           │
│ 25%        ┆ 2557.0     ┆ null   ┆ null      ┆ … ┆ 2025-03-2 ┆ 1899-12-3 ┆ -5.199978 ┆ -80.65328 │
│            ┆            ┆        ┆           ┆   ┆ 0         ┆ 1 06:18:3 ┆           ┆ 8         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 3.302000  ┆           ┆           │
│ 50%        ┆ 5151.0     ┆ null   ┆ null      ┆ … ┆ 2025-06-1 ┆ 1899-12-3 ┆ -5.188223 ┆ -80.62968 │
│            ┆            ┆        ┆           ┆   ┆ 9         ┆ 1 12:52:5 ┆           ┆           │
│            ┆            ┆        ┆           ┆   ┆           ┆ 0.080000  ┆           ┆           │
│ 75%        ┆ 8107.0     ┆ null   ┆ null      ┆ … ┆ 2025-09-2 ┆ 1899-12-3 ┆ -5.177773 ┆ -80.59925 │
│            ┆            ┆        ┆           ┆   ┆ 5         ┆ 1 18:24:5 ┆           ┆ 3         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 4.476000  ┆           ┆           │
│ max        ┆ 10318.0    ┆ S84    ┆ AG: Conex ┆ … ┆ 2026-01-0 ┆ 1899-12-3 ┆ -5.139109 ┆ -5.143028 │
│            ┆            ┆        ┆ iones Dom ┆   ┆ 4         ┆ 1 23:58:4 ┆           ┆           │
│            ┆            ┆        ┆ iciliaria ┆   ┆           ┆ 5.800000  ┆           ┆           │
│            ┆            ┆        ┆ s  …      ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [129]:
# 2. Inconsistencias gráficas: switch lat y long

#mal_coords = pl.when()

df_02 = df_02.with_columns(
    pl.when((pl.col('latitud') <= -6) | (pl.col('longitud') >= -82)).then(pl.col('longitud')).otherwise(pl.col('latitud')),
    pl.when((pl.col('latitud') <= -6) | (pl.col('longitud') >= -82)).then(pl.col('latitud')).otherwise(pl.col('longitud'))
)

df_02.unique()
df_02.head()

shape: (5, 12)
┌──────────┬────────┬───────────────┬─────┬───┬────────────┬──────────────┬───────────┬────────────┐
│ CONEXION ┆ SECTOR ┆ CDESTIPSER    ┆ MES ┆ … ┆ fecha_fin  ┆ hora_fin     ┆ latitud   ┆ longitud   │
│ ---      ┆ ---    ┆ ---           ┆ --- ┆   ┆ ---        ┆ ---          ┆ ---       ┆ ---        │
│ i64      ┆ str    ┆ str           ┆ i64 ┆   ┆ date       ┆ datetime[ms] ┆ f64       ┆ f64        │
╞══════════╪════════╪═══════════════╪═════╪═══╪════════════╪══════════════╪═══════════╪════════════╡
│ 3776     ┆ S75    ┆ AG:           ┆ 1   ┆ … ┆ 2025-02-02 ┆ 1899-12-31   ┆ -5.187439 ┆ -80.626533 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 09:42:52.760 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
│ 1241     ┆ S80    ┆ AG:           ┆ 6   ┆ … ┆ 2025-06-21 ┆ 1899-12-31   ┆ -5.197627 ┆ -80.659583 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 05:50:08.284 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
│ 4080     ┆ S67    ┆ AG:           ┆ 10  ┆ … ┆ 2025-10-08 ┆ 1899-12-31   ┆ -5.178034 ┆ -80.590859 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 19:08:12.560 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
│ 3209     ┆ S35    ┆ AG:           ┆ 2   ┆ … ┆ 2025-02-17 ┆ 1899-12-31   ┆ -5.194231 ┆ -80.666403 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 07:53:54.632 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
│ 7756     ┆ S83    ┆ AG:           ┆ 6   ┆ … ┆ 2025-06-07 ┆ 1899-12-31   ┆ -5.165495 ┆ -80.647779 │
│          ┆        ┆ Conexiones    ┆     ┆   ┆            ┆ 21:29:58.176 ┆           ┆            │
│          ┆        ┆ Domiciliarias ┆     ┆   ┆            ┆              ┆           ┆            │
│          ┆        ┆ …             ┆     ┆   ┆            ┆              ┆           ┆            │
└──────────┴────────┴───────────────┴─────┴───┴────────────┴──────────────┴───────────┴────────────┘

In [130]:
df_02.describe()

shape: (9, 13)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ CONEXION   ┆ SECTOR ┆ CDESTIPSE ┆ … ┆ fecha_fin ┆ hora_fin  ┆ latitud   ┆ longitud  │
│ ---        ┆ ---        ┆ ---    ┆ R         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ f64        ┆ str    ┆ ---       ┆   ┆ str       ┆ str       ┆ f64       ┆ f64       │
│            ┆            ┆        ┆ str       ┆   ┆           ┆           ┆           ┆           │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 722.0      ┆ 722    ┆ 722       ┆ … ┆ 722       ┆ 722       ┆ 722.0     ┆ 722.0     │
│ null_count ┆ 0.0        ┆ 0      ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 5179.53601 ┆ null   ┆ null      ┆ … ┆ 2025-06-2 ┆ 1899-12-3 ┆ -12.71039 ┆ -73.10947 │
│            ┆ 1          ┆        ┆           ┆   ┆ 6 09:16:2 ┆ 1 12:25:1 ┆ 2         ┆ 6         │
│            ┆            ┆        ┆           ┆   ┆ 7.257617  ┆ 5.874000  ┆           ┆           │
│ std        ┆ 3011.43187 ┆ null   ┆ null      ┆ … ┆ null      ┆ null      ┆ 22.62264  ┆ 22.622416 │
│            ┆ 2          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ min        ┆ 15.0       ┆ S10    ┆ AG: Conex ┆ … ┆ 2025-01-0 ┆ 1899-12-3 ┆ -80.68765 ┆ -80.69132 │
│            ┆            ┆        ┆ iones Dom ┆   ┆ 3         ┆ 1 00:01:5 ┆ 3         ┆ 2         │
│            ┆            ┆        ┆ iciliaria ┆   ┆           ┆ 8.439000  ┆           ┆           │
│            ┆            ┆        ┆ s  …      ┆   ┆           ┆           ┆           ┆           │
│ 25%        ┆ 2557.0     ┆ null   ┆ null      ┆ … ┆ 2025-03-2 ┆ 1899-12-3 ┆ -5.199978 ┆ -80.65328 │
│            ┆            ┆        ┆           ┆   ┆ 0         ┆ 1 06:18:3 ┆           ┆ 8         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 3.302000  ┆           ┆           │
│ 50%        ┆ 5151.0     ┆ null   ┆ null      ┆ … ┆ 2025-06-1 ┆ 1899-12-3 ┆ -5.188223 ┆ -80.62968 │
│            ┆            ┆        ┆           ┆   ┆ 9         ┆ 1 12:52:5 ┆           ┆           │
│            ┆            ┆        ┆           ┆   ┆           ┆ 0.080000  ┆           ┆           │
│ 75%        ┆ 8107.0     ┆ null   ┆ null      ┆ … ┆ 2025-09-2 ┆ 1899-12-3 ┆ -5.177773 ┆ -80.59925 │
│            ┆            ┆        ┆           ┆   ┆ 5         ┆ 1 18:24:5 ┆           ┆ 3         │
│            ┆            ┆        ┆           ┆   ┆           ┆ 4.476000  ┆           ┆           │
│ max        ┆ 10318.0    ┆ S84    ┆ AG: Conex ┆ … ┆ 2026-01-0 ┆ 1899-12-3 ┆ -5.139109 ┆ -5.143028 │
│            ┆            ┆        ┆ iones Dom ┆   ┆ 4         ┆ 1 23:58:4 ┆           ┆           │
│            ┆            ┆        ┆ iciliaria ┆   ┆           ┆ 5.800000  ┆           ┆           │
│            ┆            ┆        ┆ s  …      ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### Reto 2

In [131]:
# 1. Ranking de roturas y fugas (por sector)

#df_02_ordered = df_02.with_columns(group_count=pl.col('SECTOR').count().over('SECTOR')).sort('group_count', descending=True)
df_02_ordered = df_02.sort(pl.col('SECTOR').count().over('SECTOR'), descending=True)
df_02_ordered.head()

shape: (5, 12)
┌──────────┬────────┬──────────────┬─────┬───┬────────────┬──────────────┬────────────┬────────────┐
│ CONEXION ┆ SECTOR ┆ CDESTIPSER   ┆ MES ┆ … ┆ fecha_fin  ┆ hora_fin     ┆ latitud    ┆ longitud   │
│ ---      ┆ ---    ┆ ---          ┆ --- ┆   ┆ ---        ┆ ---          ┆ ---        ┆ ---        │
│ i64      ┆ str    ┆ str          ┆ i64 ┆   ┆ date       ┆ datetime[ms] ┆ f64        ┆ f64        │
╞══════════╪════════╪══════════════╪═════╪═══╪════════════╪══════════════╪════════════╪════════════╡
│ 8963     ┆ S84    ┆ AG:          ┆ 6   ┆ … ┆ 2025-06-21 ┆ 1899-12-31   ┆ -5.181692  ┆ -80.651714 │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 13:23:14.324 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
│ 9058     ┆ S84    ┆ AG:          ┆ 12  ┆ … ┆ 2025-12-14 ┆ 1899-12-31   ┆ -5.185349  ┆ -80.652763 │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 02:35:01.011 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
│ 8975     ┆ S84    ┆ AG:          ┆ 9   ┆ … ┆ 2025-09-07 ┆ 1899-12-31   ┆ -5.202329  ┆ -80.652763 │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 09:25:09.448 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
│ 9099     ┆ S84    ┆ AG:          ┆ 10  ┆ … ┆ 2025-10-18 ┆ 1899-12-31   ┆ -5.190051  ┆ -80.6365   │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 23:30:42.352 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
│ 8997     ┆ S84    ┆ AG:          ┆ 5   ┆ … ┆ 2025-06-03 ┆ 1899-12-31   ┆ -80.619453 ┆ -5.209904  │
│          ┆        ┆ Conexiones   ┆     ┆   ┆            ┆ 04:46:12.774 ┆            ┆            │
│          ┆        ┆ Domiciliaria ┆     ┆   ┆            ┆              ┆            ┆            │
│          ┆        ┆ s  …         ┆     ┆   ┆            ┆              ┆            ┆            │
└──────────┴────────┴──────────────┴─────┴───┴────────────┴──────────────┴────────────┴────────────┘